/**
 * Worker-side runtime (as a plain-JS string) + host-side script validation.
 *
 * The worker source is a literal string so spawning needs no file resolution:
 *   new Worker(WORKER_SOURCE, { eval: true })
 * followed by an init message {type:"init", script, args, meta}.
 *
 * Worker isolation is an AVAILABILITY boundary (runaway scripts terminate),
 * not a security sandbox — user scripts are trusted code (see README).
 *
 * Builder B module.
 */

/**
 * The complete worker-side runtime. Plain JS (no backticks / template
 * literals inside — this file embeds it as a TS template string).
 *
 * Semantics:
 *  - {type:"init", script, args, meta} -> runs script as `(async () => { ... })()`
 *    with injected globals (agent/parallel/pipeline/phase/progress/workflow/
 *    sleep/console/args/meta); posts {type:"done", ok, value|error}.
 *  - agent()/workflow() post {type:"call", id, fn, args} and resolve on
 *    {type:"result", id, ok, value|error}.
 *  - parallel: Promise.all with per-thunk catch -> null + console.log.
 *  - pipeline: per-item async chains; stage throw -> item null + console.log.
 *  - workflow(name, args) executes the composed script at depth+1; the depth
 *    is passed to the host which enforces the cap (depth > 0 rejected).
 *  - sleep bounded to 60s per call; console forwarded as log events.
 *  - done values are sanitized (functions/symbols/undefined stripped,
 *    bigint -> string, cycles -> "[circular]") so structured clone cannot throw.
 *  - unhandledRejection/uncaughtException -> done ok:false (single-shot).
 */
export const WORKER_SOURCE = `
"use strict";
// ultracode worker runtime (generated by src/worker-script.ts)
var wt = null;
try { wt = require("node:worker_threads"); } catch (e) { wt = null; }
var port = wt ? wt.parentPort : null;
if (!port) throw new Error("worker runtime: no parentPort");

var started = false;
var settled = false;
var callSeq = 0;
var pending = new Map();

function post(msg) {
  try { port.postMessage(msg); } catch (e) { /* host gone */ }
}

function errMsg(e) {
  if (e instanceof Error) return e.message;
  return String(e);
}

function fmt(v) {
  if (typeof v === "string") return v;
  if (v instanceof Error) return v.message;
  try { return JSON.stringify(v); } catch (e) { return String(v); }
}

function sanitize(v, seen) {
  if (v === null) return null;
  var t = typeof v;
  if (t === "string" || t === "number" || t === "boolean") return v;
  if (t === "bigint") return String(v);
  if (t === "undefined" || t === "function" || t === "symbol") return null;
  if (t === "object") {
    if (seen.has(v)) return "[circular]";
    seen.add(v);
    var out;
    if (Array.isArray(v)) {
      out = new Array(v.length);
      for (var ai = 0; ai < v.length; ai++) out[ai] = sanitize(v[ai], seen);
    } else {
      out = {};
      var keys = Object.keys(v);
      for (var ki = 0; ki < keys.length; ki++) {
        var k = keys[ki];
        var val = v[k];
        var vt = typeof val;
        if (vt === "undefined" || vt === "function" || vt === "symbol") continue;
        out[k] = sanitize(val, seen);
      }
    }
    seen.delete(v); // ancestor tracking: shared refs are NOT cycles
    return out;
  }
  return null;
}

function callHost(fn, args) {
  return new Promise(function (resolve, reject) {
    callSeq += 1;
    var id = callSeq;
    var entry = { resolve: resolve, reject: reject };
    pending.set(id, entry);
    try {
      port.postMessage({ type: "call", id: id, fn: fn, args: args });
    } catch (e) {
      // Structured-clone failure (uncloneable arg): drop the pending entry and
      // reject so agent()/workflow() fail promptly instead of hanging forever.
      pending.delete(id);
      reject(new Error("ultracode: bridge call could not be delivered: " + errMsg(e)));
    }
  });
}

var scriptConsole = {
  log: function () {
    var parts = [];
    for (var i = 0; i < arguments.length; i++) parts.push(fmt(arguments[i]));
    post({ type: "event", kind: "log", data: parts.join(" ") });
  },
};

function runBody(script, globals) {
  var keys = Object.keys(globals);
  var values = keys.map(function (k) { return globals[k]; });
  var body = '"use strict"; return (async () => {\\n' + script + '\\n})();';
  var fn = new Function(...keys, body);
  return fn(...values);
}

function makeStep(stage, index) {
  return function (value) { return stage(value, index); };
}

// Network/DOM escape hatches are shadowed by throwing stubs (defense in depth
// on top of host-side script validation, which bans these identifiers).
function unavailableStub(name) {
  return function () {
    throw new Error("ultracode: " + name + " is not available in workflow scripts");
  };
}

function makeGlobals(depth, args, meta) {
  return {
    agent: function (prompt, opts) {
      return callHost("agent", [prompt, opts || {}]);
    },
    fetch: unavailableStub("fetch"),
    WebSocket: unavailableStub("WebSocket"),
    XMLHttpRequest: unavailableStub("XMLHttpRequest"),
    navigator: unavailableStub("navigator"),
    importScripts: unavailableStub("importScripts"),
    parallel: function (thunks) {
      return Promise.all(thunks.map(function (thunk) {
        return Promise.resolve().then(thunk).catch(function (e) {
          scriptConsole.log("parallel thunk failed: " + errMsg(e));
          return null;
        });
      }));
    },
    pipeline: function (items) {
      var stages = Array.prototype.slice.call(arguments, 1);
      return Promise.all(items.map(function (item, index) {
        var chain = Promise.resolve(item);
        for (var si = 0; si < stages.length; si++) chain = chain.then(makeStep(stages[si], index));
        return chain.catch(function (e) {
          scriptConsole.log("pipeline item " + index + " failed: " + errMsg(e));
          return null;
        });
      }));
    },
    phase: function (name) {
      post({ type: "event", kind: "phase", data: String(name) });
    },
    progress: function (text) {
      post({ type: "event", kind: "progress", data: String(text) });
    },
    workflow: function (name, wfArgs) {
      return callHost("workflow", [name, wfArgs === undefined ? null : wfArgs, depth]).then(function (composed) {
        if (!composed || typeof composed.script !== "string") {
          throw new Error("workflow bridge returned no script");
        }
        return runScript(composed.script, composed.meta || {}, wfArgs, depth + 1);
      });
    },
    sleep: function (ms) {
      var n = Math.max(0, Math.min(Number(ms) || 0, 60000));
      return new Promise(function (resolve) { setTimeout(resolve, n); });
    },
    console: scriptConsole,
    args: args,
    meta: meta || {},
  };
}

async function runScript(script, meta, args, depth) {
  var globals = makeGlobals(depth, args, meta);
  return await runBody(script, globals);
}

function finish(ok, value, error) {
  if (settled) return;
  // Build the completion payload FIRST (a throwing getter in the return value
  // must become a failure payload, not a lost done message + watchdog wait).
  var payload;
  try {
    if (ok) payload = { type: "done", ok: true, value: sanitize(value, new WeakSet()) };
    else payload = { type: "done", ok: false, error: error };
  } catch (e) {
    payload = { type: "done", ok: false, error: "completion payload could not be built: " + errMsg(e) };
  }
  settled = true;
  post(payload);
}

port.on("message", function (msg) {
  if (!msg || typeof msg !== "object") return;
  if (msg.type === "init" && !started) {
    started = true;
    Promise.resolve()
      .then(function () { return runScript(msg.script, msg.meta, msg.args, 0); })
      .then(function (value) { finish(true, value, undefined); })
      .catch(function (e) { finish(false, undefined, errMsg(e)); });
    return;
  }
  if (msg.type === "result") {
    var entry = pending.get(msg.id);
    if (!entry) return;
    pending.delete(msg.id);
    if (msg.ok) entry.resolve(msg.value);
    else entry.reject(new Error(msg.error));
  }
});

process.on("unhandledRejection", function (e) {
  finish(false, undefined, "unhandled rejection: " + errMsg(e));
});
process.on("uncaughtException", function (e) {
  finish(false, undefined, "uncaught exception: " + errMsg(e));
});
`

// ---------------------------------------------------------------------------
// Host-side validation (runs BEFORE spawn)
// ---------------------------------------------------------------------------

export type ScriptCheck = { ok: true } | { ok: false; error: string }

export const MAX_SCRIPT_CHARS = 512 * 1024

/** Identifiers that must not be referenced anywhere in a user script. */
const BANNED_IDENTIFIERS = new Set([
  "process",
  "require",
  "globalThis",
  "Function",
  "WebAssembly",
  // network/DOM escape hatches (shadowed by throwing stubs in the worker too)
  "fetch",
  "WebSocket",
  "XMLHttpRequest",
  "navigator",
  "importScripts",
])

function isIdentStart(c: string): boolean {
  return (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c === "_" || c === "$"
}

function isIdentPart(c: string): boolean {
  return isIdentStart(c) || (c >= "0" && c <= "9")
}

function skipJsString(src: string, start: number, quote: string): number {
  let i = start + 1
  while (i < src.length) {
    const c = src[i]
    if (c === "\\") {
      i += 2
      continue
    }
    if (c === quote) return i + 1
    if (quote !== "`" && c === "\n") return i // unterminated line string
    i++
  }
  return i
}

function skipWsAndComments(src: string, start: number): number {
  let i = start
  while (i < src.length) {
    const c = src[i]
    if (c === " " || c === "\t" || c === "\n" || c === "\r") {
      i++
      continue
    }
    if (c === "/" && src[i + 1] === "/") {
      i += 2
      while (i < src.length && src[i] !== "\n") i++
      continue
    }
    if (c === "/" && src[i + 1] === "*") {
      i += 2
      while (i < src.length && !(src[i] === "*" && src[i + 1] === "/")) i++
      i = Math.min(src.length, i + 2)
      continue
    }
    break
  }
  return i
}

function nextMeaningfulChar(src: string, start: number): string {
  const i = skipWsAndComments(src, start)
  return i < src.length ? src[i] : ""
}

/**
 * Validate a user script before spawning a worker.
 *
 * Rejects: ESM `export` / `import` at statement starts (and dynamic `import(`),
 * references to `process` / `require` / `globalThis` / `Function` /
 * `WebAssembly` / `fetch` / `WebSocket` / `XMLHttpRequest` / `navigator` /
 * `importScripts`, and scripts over 512 KB. `while (true) {}` and friends are
 * ALLOWED — worker termination handles runaway scripts (availability boundary).
 *
 * The tokenizer is deliberately simple (strings / template literals / comments
 * are skipped; regex literals are not distinguished) — it must not false-positive
 * on words like "import" inside strings, and it does not need to be perfect.
 */
export function validateScriptSource(src: string): ScriptCheck {
  if (typeof src !== "string") return { ok: false, error: "script must be a string" }
  if (src.trim() === "") return { ok: false, error: "script is empty" }
  if (src.length > MAX_SCRIPT_CHARS) {
    return { ok: false, error: `script too large: ${src.length} chars (max ${MAX_SCRIPT_CHARS})` }
  }

  let i = 0
  const n = src.length
  // "" = start of script, ";" / "}" = statement-terminating token, else "x"
  let prev = ""

  while (i < n) {
    const c = src[i]
    if (c === " " || c === "\t" || c === "\n" || c === "\r") {
      i++
      continue
    }
    if (c === "/" && src[i + 1] === "/") {
      i = skipWsAndComments(src, i)
      continue
    }
    if (c === "/" && src[i + 1] === "*") {
      i = skipWsAndComments(src, i)
      continue
    }
    if (c === '"' || c === "'" || c === "`") {
      i = skipJsString(src, i, c)
      prev = "x"
      continue
    }
    if (isIdentStart(c)) {
      let j = i + 1
      while (j < n && isIdentPart(src[j])) j++
      const word = src.slice(i, j)
      if (BANNED_IDENTIFIERS.has(word)) {
        return { ok: false, error: `forbidden reference: "${word}" is not allowed in workflow scripts` }
      }
      const atStatementStart = prev === "" || prev === ";" || prev === "}"
      if (word === "import" && (atStatementStart || nextMeaningfulChar(src, j) === "(")) {
        return { ok: false, error: "import/export statements are not allowed — a workflow script is an async function body (plain JS, no ESM)" }
      }
      if (word === "export" && atStatementStart) {
        return { ok: false, error: "import/export statements are not allowed — a workflow script is an async function body (plain JS, no ESM)" }
      }
      prev = "x"
      i = j
      continue
    }
    prev = c === ";" || c === "}" ? c : "x"
    i++
  }
  return { ok: true }
}
